### 앞 파일에 도로폭 추가

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('../data/인천광역시_차로폭, 차로수_현황_20211231.csv',encoding='cp949')
df

,번호,도로명,폭원(미터),연장(미터),면적(제곱미터),기점,종점,비고
0,1,가람로,25.0,542,13550,오류동 1434,서측구역계,검단산단
1,2,가석로156번길,21.0,530,11130,고속도로측도교차점,건지로348번길,NaN
2,3,가정로151번길,25.0,365,9125,염곡로교차점,가정로교차점,NaN
3,4,가정로152번길,25.0,330,8250,가정로교차점,고속도로측도교차점,NaN
4,5,가정로98번길,25.0,320,8000,가정로교차점,고속도로측도교차점,NaN
...,...,...,...,...,...,...,...,...
189,190,염전로168번길,23.0,177,3983,대2-1(염전로),중3-317(염전로144번안길),NaN
190,191,서운산업로,23.0,153,3595,광로2-5,중로3-73,서운산단
191,192,서운산단로,23.0,429,10081,광로3-9,중로1-656,서운산단
192,193,북항배후부지도로(대2-116),30.0,602,18060,대로2-116,대1-17,북항배후단지
193,194,중-1-176,23.4,14294,334480,서구 시청동,계양동 평동1-1,경인아라뱃길

In [2]:
df.drop(['번호','기점','종점','비고', '연장(미터)','면적(제곱미터)'], axis=1, inplace=True)
df

                  도로명  폭원(미터)
0                 가람로    25.0
1            가석로156번길    21.0
2            가정로151번길    25.0
3            가정로152번길    25.0
4             가정로98번길    25.0
..                ...     ...
189          염전로168번길    23.0
190             서운산업로    23.0
191             서운산단로    23.0
192  북항배후부지도로(대2-116)    30.0
193           중-1-176    23.4

[194 rows x 2 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   도로명     194 non-null    object
 1   폭원(미터)  194 non-null    float64
dtypes: float64(1), object(1)
memory usage: 3.2+ KB

In [4]:
df.head(17)

         도로명  폭원(미터)
0        가람로    25.0
1   가석로156번길    21.0
2   가정로151번길    25.0
3   가정로152번길    25.0
4    가정로98번길    25.0
5       갑문2로    26.0
6    갑문4로(1)    26.0
7    갑문4로(2)    26.0
8        갑문로    35.0
9     거첨로(1)    33.0
10    거첨로(2)    24.0
11       건지로    30.0
12       검단로    25.0
13      검바위로    27.5
14      경명대로    40.0
15      경원대로    35.0
16       경인로    35.0

In [5]:
df['폭원(미터)'] = pd.to_numeric(df['폭원(미터)'])

In [6]:
df.rename(columns = {'폭원(미터)':'도로폭'}, inplace=True)

In [7]:
df['도로폭_숫자'] = df['도로폭']
df

                  도로명   도로폭  도로폭_숫자
0                 가람로  25.0    25.0
1            가석로156번길  21.0    21.0
2            가정로151번길  25.0    25.0
3            가정로152번길  25.0    25.0
4             가정로98번길  25.0    25.0
..                ...   ...     ...
189          염전로168번길  23.0    23.0
190             서운산업로  23.0    23.0
191             서운산단로  23.0    23.0
192  북항배후부지도로(대2-116)  30.0    30.0
193           중-1-176  23.4    23.4

[194 rows x 3 columns]

In [8]:
df.loc[df['도로폭_숫자'] < 6, '도로폭_숫자'] = 1
df.loc[df['도로폭_숫자'].between(6,8,inclusive='left'),'도로폭_숫자'] = 2
df.loc[df['도로폭_숫자'].between(8,10,inclusive='left'),'도로폭_숫자'] = 3
df.loc[df['도로폭_숫자'].between(10,12,inclusive='left'),'도로폭_숫자'] = 4
df.loc[df['도로폭_숫자'].between(12,15,inclusive='left'),'도로폭_숫자'] = 5
df.loc[df['도로폭_숫자'].between(15,20,inclusive='left'),'도로폭_숫자'] = 6
df.loc[df['도로폭_숫자'].between(20,25,inclusive='left'),'도로폭_숫자'] = 7
df.loc[df['도로폭_숫자'].between(25,30,inclusive='left'),'도로폭_숫자'] = 8
df.loc[df['도로폭_숫자'].between(30,35,inclusive='left'),'도로폭_숫자'] = 9
df.loc[df['도로폭_숫자'].between(35,40,inclusive='left'),'도로폭_숫자'] = 10
df.loc[df['도로폭_숫자'].between(40,50,inclusive='left'),'도로폭_숫자'] = 11
df.loc[df['도로폭_숫자'].between(50,70,inclusive='left'),'도로폭_숫자'] = 12
df.loc[df['도로폭_숫자'] > 70, '도로폭_숫자'] = 13
df

                  도로명   도로폭  도로폭_숫자
0                 가람로  25.0     8.0
1            가석로156번길  21.0     7.0
2            가정로151번길  25.0     8.0
3            가정로152번길  25.0     8.0
4             가정로98번길  25.0     8.0
..                ...   ...     ...
189          염전로168번길  23.0     7.0
190             서운산업로  23.0     7.0
191             서운산단로  23.0     7.0
192  북항배후부지도로(대2-116)  30.0     9.0
193           중-1-176  23.4     7.0

[194 rows x 3 columns]

In [9]:
df.to_csv('../data/전처리데이터/부평구 도로폭.csv', encoding = 'cp949', index=None)

### 버스수

In [10]:
df2 = pd.read_csv('../data/전처리데이터/부평구 정류장명 및 위치와 버스_최종.csv',encoding='cp949')
df2

,정류소명,정류소아이디,정류소주소,노선아이디,정류소번호,노선번호,평균 배차 간격,최대 배차 간격,도로명,도로폭,도로폭_숫자
0,진산과학고등학교,166000915,인천광역시 부평구 굴포로 208 버스정류장,165000112,40915,"['565', '555', '558']",13.33,17,굴포로,30.0,9.0
1,삼산주공1단지(상가앞),166000908,인천광역시 부평구 평천로 443 버스정류장,165000013,40908,"['10', '34']",13.00,15,평천로,25.0,8.0
2,희망체육공원입구,166000912,인천광역시 부평구 경인로 840 버스정류장,165000107,40912,"['561', '561', '562', '562', '557', '557', '55...",23.00,35,경인로,35.0,10.0
3,인천성모병원종점지주차장,166000919,인천광역시 부평구 동수로 68 버스정류장,165000053,40919,"['79', '1', '43']",16.00,18,동수로,20.0,7.0
4,열우물보조경기장주차장,166000916,인천광역시 부평구 열우물로150번길 64 버스정류장,165000111,40916,['564-1'],24.00,24,열우물로,27.5,8.0
...,...,...,...,...,...,...,...,...,...,...,...
640,종근당,166000005,인천광역시 부평구 백범로 486 버스정류장,165000216,40005,['103-1'],15.00,15,백범로,35.0,10.0
641,형제마트,166000004,인천광역시 부평구 정석로 6 버스정류장,165000110,40004,['564'],12.00,12,정석로,10.0,4.0
642,동암사거리,166000003,인천광역시 부평구 백범로 452 버스정류장,165000219,40003,"['303', '304', '103', '103-1', '42', '592', '3...",15.57,20,백범로,35.0,10.0
643,종근당,166000002,인천광역시 부평구 백범로 481 버스정류장,165000216,40002,['103-1'],15.00,15,백범로,35.0,10.0
644,동암사거리,166000001,인천광역시 부평구 백범로 453 버스정류장,165000219,40001,"['303', '304', '103', '103-1', '42', '592', '62']",14.00,20,백범로,35.0,10.0

In [11]:
df2['노선번호'] = df2['노선번호'].str.split(', ').to_list()

In [12]:
for i in df2['노선번호']:
    for j in i:
        print(j)

['565'
'555'
'558']
['10'
'34']
['561'
'561'
'562'
'562'
'557'
'557'
'557A'
'557A']
['79'
'1'
'43']
['564-1']
['24-1번'
'20'
'20A']
['79'
'1'
'43']
['557A']
['14-1번'
'561'
'562'
'79'
'1'
'37'
'43']
['14-1번'
'561'
'562'
'79'
'37']
['306'
'307']
['564-1']
['564-1']
['565'
'555'
'558']
['569'
'570']
['569'
'570']
['569'
'570']
['592'
'586'
'588']
['586'
'588']
['45'
'67-1번'
'526']
['24-1번']
['561']
['556']
['14-1번'
'47'
'11'
'526'
'급행97'
'인천e음61']
['14-1번'
'47'
'11'
'526'
'급행97'
'인천e음61']
['67-1번'
'526']
['14-1번'
'47'
'11']
['35']
['302'
'1601'
'12']
['302'
'302B'
'551'
'1601'
'12']
['565'
'551']
['34']
['14-1번'
'20'
'20A']
['302'
'급행95'
'급행97']
['582'
'43-1번'
'560']
['14-1번'
'47'
'11'
'526'
'인천e음61']
['14-1번'
'47'
'11'
'526'
'인천e음61']
['14-1번'
'47'
'11'
'526'
'급행97'
'인천e음61']
['526'
'인천e음61']
['526'
'인천e음61']
['14-1번'
'47'
'11'
'526'
'급행97'
'인천e음61']
['14-1번'
'47'
'11'
'526'
'인천e음61']
['14-1번'
'47'
'11'
'526'
'인천e음61']
['539'
'564-2']
['539'
'564-2']
['539'
'564-2']
['564-2']
['539'
'564-2']
['539'
'564-2']
['565'
'555']
['14-1번'
'561'
'562'
'37']
['14-1번'
'2'
'67-1번']
['14-1번'
'47'
'11'
'526'
'급행97'
'인천e음61']
['14-1번'
'47'
'11'
'526'
'급행97'
'인천e음61']
['556']
['34'
'556']
['530'
'564-1']
['530'
'530'
'564-1']
['14-1번'
'14-1번'
'586'
'586'
'588'
'588']
['103'
'35'
'45'
'47'
'585'
'586'
'1'
'112'
'43'
'43-1번'
'24']
['14-1번'
'561'
'562'
'1'
'37'
'43']
['103-1'
'14-1번'
'14-1번'
'47'
'47'
'11'
'11'
'16-1번'
'8'
'8A'
'30']
['103-1'
'14-1번'
'47'
'11'
'16-1번'
'8'
'8A'
'30']
['111'
'111-2'
'582'
'584-1'
'34'
'46'
'12'
'30'
'583']
['556']
['565'
'28'
'555'
'558'
'571']
['10'
'565'
'28'
'34'
'37'
'555'
'558'
'571']
['526'
'12'
'급행97'
'인천e음61']
['12']
['556'
'571'
'571']
['34']
['12']
['14-1번'
'47'
'11'
'12']
['47'
'1'
'112'
'43'
'43-1번']
['47'
'1'
'112'
'43'
'43-1번']
['47'
'43'
'43-1번']
['급행95'
'47'
'1'
'46'
'급행97'
'43']
['급행95'
'47'
'46'
'급행97']
['14-1번'
'526']
['45'
'67-1번'
'526']
['10'
'급행95'
'111-2'
'87'
'9300'
'46'
'급행97'
'558']
['10'
'급행95'
'24-1번'
'28'
'46'
'급행97']
['10'
'급행95'
'87'
'24-1번'
'28'
'급행97']
['10'
'87'
'24-1번']
['45'
'585']
['35'
'45'
'585']
['1500']
['551']
['1200']
['579']
['564']
['565'
'28']
['565'
'24-1번'
'28']
['530'
'564'
'564'
'593']
['14-1번'
'45'
'37']
['556'
'558']
['533'
'532'
'535'
'536'
'537']
['565'
'555'
'558']
['103'
'35'
'45'
'47'
'585'
'1200'
'586'
'1'
'112'
'43'
'43-1번'
'24']
['103'
'35'
'45'
'47'
'585'
'582'
'1200'
'586'
'1'
'112'
'43'
'43-1번'
'24'
'560']
['103'
'2'
'551'
'11'
'28'
'1']
['574'
'582'
'1'
'43-1번'
'560']
['103-1'
'14-1번'
'561'
'562'
'47'
'79'
'11'
'37'
'급행97']
['103-1'
'14-1번'
'561'
'562'
'47'
'79'
'11'
'37'
'급행97']
['302'
'302B'
'574'
'35'
'10'
'2'
'1400'
'111'
'111-2'
'570'
'582'
'23'
'24-1번'
'1'
'34'
'30'
'112'
'556'
'557'
'557A']
['302'
'302B'
'35'
'10'
'2'
'1400'
'111'
'111-2'
'23'
'24-1번'
'34'
'30'
'112'
'556'
'564'
'564-2']
['103'
'14-1번'
'567'
'20'
'20A'
'556']
['1200'
'11'
'24-1번'
'67-1번'
'28'
'556'
'24']
['14-1번'
'2'
'567'
'1200'
'67-1번']
['35'
'10'
'급행95'
'565'
'24-1번'
'급행97']
['562'
'526'
'12']
['579']
['302'
'561'
'45'
'47'
'565'
'586'
'11'
'1'
'46'
'12'
'43'
'558'
'579']
['37'
'556']
['14-1번'
'1200'
'67-1번']
['103'
'14-1번'
'567'
'20'
'20A'
'556']
['562'
'67-1번']
['565']
['급행95'
'급행97']
['558']
['9300']
['574'
'585']
['557']
['557']
['557']
['570']
['557'
'557A']
['557']
['569']
['569']
['569']
['569'
'570']
['562'
'526']
['67-1번']
['539'
'564'
'564-1'
'564-2']
['564-1']
['564-1']
['539'
'564'
'564-1'
'564-2']
['564']
['10'
'급행95'
'111'
'111B'
'24-1번'
'급행97']
['79'
'34']
['565'
'28'
'555'
'558'
'571']
['565'
'28'
'555'
'558'
'571']
['10'
'565'
'28'
'34'
'37'
'555'
'558'
'571']
['10'
'565'
'28'
'34'
'37'
'555'
'558'
'571']
['555'
'571']
['565'
'28'
'555'
'558'
'571']
['10'
'565'
'28'
'34'
'37'
'555'
'558'
'571']
['565'
'28'
'555'
'558'
'571']
['10'
'565'
'28'
'34'
'37'
'555'
'558'
'571']
['10'
'565'
'34'
'37'
'558']
['28'
'571']
['565'
'555'
'558']
['28'
'555'
'571']
['582']
['582'
'571']
['571']
['565'
'28'
'555'
'556'
'558']
['10'
'565'
'28'
'37'
'555'
'558']
['10'
'565'
'34'
'37'
'558']
['582'
'571']
['581']
['582'
'581']
['10'
'34'
'37'
'556']
['급행95'
'79'
'87'
'24-1번'
'급행97']
['556']
['급행95'
'111'
'79'
'87'
'24-1번'
'555'
'급행97']
['10'
'565'
'34'
'37'
'558']
['582'
'571'
'581']
['582'
'581']
['556']
['79'
'9300'
'555']
['10'
'34'
'526'
'555']
['111'
'111B'
'87'
'9300'
'24-1번'
'571']
['565'
'37'
'526'
'556'
'558']
['526']
['584-1'
'30'
'583']
['10'
'79'
'34'
'526']
['526'
'555']
['584-1'
'30'
'583']
['565'
'37'
'526'
'556'
'558']
['565'
'555'
'558'
'인천e음61']
['급행95'
'111'
'87'
'24-1번'
'급행97']
['79']
['79']
['34'
'526'
'555'
'571']
['582'
'571'
'581']
['565'
'558'
'인천e음61']
['582'
'581']
['565'
'37'
'526'
'556'
'558']
['34'
'526'
'555']
['67-1번'
'34'
'526'
'555']
['585']
['12']
['12']
['1400'
'9500']
['12']
['12']
['2']
['2']
['585'
'12']
['12']
['37'
'526'
'558']
['565'
'37'
'526'
'인천e음61']
['79']
['79']
['556']
['556'
'558']
['28']
['67-1번'
'571'
'581']
['584-1'
'12'
'30'
'583']
['67-1번'
'571'
'581']
['1400'
'9500'
'584-1'
'12'
'30'
'583']
['582'
'67-1번'
'34'
'526'
'555']
['582'
'67-1번'
'34'
'526'
'555']
['585'
'12']
['585'
'12']
['103'
'2'
'45'
'594'
'586']
['565']
['103'
'2'
'586']
['67-1번'
'526']
['67-1번'
'526']
['37'
'526'
'558']
['585']
['565'
'37'
'526'
'인천e음61']
['10'
'111'
'87'
'9300'
'24-1번']
['14-1번'
'594'
'551'
'526']
['103'
'14-1번'
'2'
'551'
'586'
'67-1번']
['24-1번'
'556'
'558']
['565'
'24-1번'
'556']
['565'
'79'
'37'
'526'
'558'
'인천e음61']
['103'
'2'
'67-1번']
['79'
'24-1번']
['14-1번'
'594'
'551'
'526']
['111'
'111B'
'556']
['67-1번'
'571'
'581']
['79'
'24-1번']
['565'
'79'
'28']
['14-1번'
'594'
'551'
'526']
['14-1번'
'551'
'586']
['79'
'28'
'558']
['1400'
'582'
'584-1'
'34'
'555'
'12'
'30'
'583']
['67-1번'
'571'
'581']
['585']
['111'
'46'
'556']
['67-1번'
'526']
['67-1번'
'526']
['111'
'111-2'
'46']
['111'
'111B']
['14-1번'
'594'
'551'
'586'
'588'
'526']
['1400'
'582'
'584-1'
'34'
'555'
'12'
'30'
'583']
['14-1번'
'594'
'551'
'526']
['551'
'526']
['14-1번'
'594'
'551'
'526']
['592'
'594'
'551'
'526']
['556']
['35']
['111'
'111B']
['24-1번'
'28'
'558']
['111'
'111-2'
'46']
['67-1번'
'556'
'571'
'581']
['67-1번'
'571'
'581']
['1200'
'9300']
['556']
['592'
'526']
['103'
'14-1번'
'35'
'2'
'67-1번']
['562'
'565'
'79'
'526'
'558'
'인천e음61']
['87'
'67-1번'
'24']
['103'
'14-1번'
'2'
'1200'
'551'
'586'
'67-1번']
['1200'
'87'
'9300'
'24']
['556']
['551'
'586']
['87'
'67-1번'
'24']
['87'
'67-1번'
'24']
['1400'
'9500'
'111'
'111-2'
'582'
'584-1'
'34'
'555'
'46'
'12'
'30'
'583']
['1400'
'9500'
'582'
'584-1'
'583']
['87'
'9300'
'67-1번'
'24']
['551'
'551']
['87'
'9300'
'67-1번'
'24']
['562'
'565'
'526'
'558'
'인천e음61']
['45'
'585'
'1200']
['35'
'45'
'585'
'1200']
['67-1번']
['562'
'565'
'526'
'558'
'인천e음61']
['565'
'526'
'558'
'인천e음61']
['67-1번'
'556'
'571'
'581']
['35'
'111-2'
'1200'
'67-1번'
'28'
'46'
'24']
['35'
'45'
'1200'
'67-1번'
'28'
'24']
['556'
'571'
'581']
['565']
['562'
'565'
'23'
'인천e음61']
['35'
'111-2'
'67-1번'
'28'
'46'
'24']
['562'
'565'
'23'
'67-1번'
'558'
'인천e음61']
['35'
'10'
'45'
'급행95'
'24-1번'
'급행97']
['23'
'67-1번'
'526'
'558']
['35'
'45'
'67-1번'
'28'
'24']
['565']
['565']
['111'
'111B'
'582'
'34'
'12'
'30']
['565']
['23'
'67-1번'
'526']
['35'
'551'
'586']
['567'
'567']
['562'
'23'
'558'
'인천e음61']
['565']
['35'
'10'
'급행95'
'24-1번'
'급행97']
['35'
'111-2'
'1200'
'28'
'46'
'24']
['79'
'1601']
['35'
'45'
'1200'
'28'
'24']
['565']
['562'
'23'
'인천e음61']
['23'
'67-1번'
'526'
'558']
['565']
['35'
'45'
'585']
['103'
'14-1번'
'2'
'567'
'1200'
'67-1번']
['35'
'45'
'585'
'567']
['579']
['103'
'14-1번'
'2'
'1200'
'551'
'586'
'67-1번']
['556'
'571'
'581']
['562'
'558'
'인천e음61']
['579']
['556'
'571'
'581']
['103'
'35'
'45'
'47'
'585'
'582'
'1200'
'586'
'1'
'112'
'43'
'43-1번'
'24']
['103'
'47'
'585'
'111-2'
'584-1'
'586'
'28'
'1'
'555'
'46'
'112'
'43'
'43-1번'
'583'
'560'
'560']
['35'
'10'
'24-1번']
['558']
['526'
'579']
['23'
'67-1번'
'526'
'558'
'579']
['565']
['558']
['551'
'586']
['565']
['79'
'579']
['35'
'10'
'45'
'24-1번']
['103'
'45'
'47'
'585'
'111'
'111-2'
'584-1'
'586'
'28'
'1'
'34'
'555'
'46'
'12'
'30'
'112'
'43'
'43-1번'
'583']
['551'
'586']
['567']
['23'
'67-1번'
'526'
'558']
['582']
['562'
'23'
'인천e음61']
['582'
'560']
['556'
'571'
'581']
['556'
'571'
'581']
['562'
'23'
'인천e음61']
['103'
'35'
'47'
'585'
'1200'
'586'
'1'
'43'
'43-1번']
['103'
'47'
'551'
'586'
'1'
'112'
'43'
'43-1번']
['103'
'47'
'551'
'586'
'1'
'112'
'43'
'43-1번']
['14-1번'
'2'
'67-1번']
['526'
'558'
'579']
['582']
['582'
'560']
['103'
'14-1번'
'2'
'567'
'551'
'586'
'67-1번']
['23'
'526'
'558'
'579']
['302'
'23'
'67-1번'
'인천e음61']
['302'
'302B'
'23'
'67-1번'
'인천e음61']
['103'
'47'
'551'
'586'
'1'
'112'
'43'
'43-1번']
['302'
'1601'
'526'
'558'
'인천e음61'
'579']
['556'
'571'
'581']
['582'
'560']
['302'
'302B'
'1601'
'526'
'558'
'인천e음61'
'579']
['565']
['582']
['103'
'2'
'551'
'11'
'28'
'1'
'43-1번']
['562'
'558'
'인천e음61']
['551'
'24']
['45'
'47'
'111'
'111-2'
'34'
'46'
'12'
'30'
'112'
'43']
['302'
'302B'
'23'
'79'
'67-1번'
'인천e음61'
'579']
['567'
'551'
'24']
['562'
'558'
'인천e음61']
['556'
'571'
'581']
['2'
'47'
'111'
'111-2'
'111B'
'11'
'34'
'46'
'12'
'30'
'112'
'43'
'43-1번']
['35'
'10'
'45'
'급행95'
'24-1번'
'급행97']
['560']
['103'
'2'
'582'
'551'
'11'
'28'
'560']
['302'
'23']
['103'
'2'
'582'
'551'
'11'
'28']
['302'
'302B'
'23']
['585'
'584-1'
'551'
'586'
'555'
'583']
['585'
'584-1'
'551'
'586'
'555'
'583']
['558']
['562'
'526'
'579']
['558']
['562'
'526'
'579']
['103'
'574'
'551'
'11'
'28']
['574'
'582'
'1']
['574'
'582'
'1'
'43-1번'
'560']
['103'
'574'
'2'
'551'
'11'
'28']
['567'
'551']
['551']
['103'
'2'
'11'
'28']
['565'
'555']
['103'
'2'
'11'
'28']
['35'
'10'
'45'
'23'
'24-1번'
'555']
['35'
'10'
'23'
'24-1번']
['556'
'571'
'581']
['556'
'571'
'581']
['302'
'302B'
'23'
'79'
'67-1번'
'인천e음61'
'579']
['2'
'45'
'1400'
'47'
'9500'
'111'
'111-2'
'11'
'34'
'46'
'12'
'30'
'112'
'43']
['79'
'인천e음61']
['560']
['103'
'567']
['2'
'1400'
'47'
'9500'
'111'
'111-2'
'111B'
'584-1'
'551'
'11'
'34'
'46'
'12'
'30'
'112'
'43'
'43-1번'
'583']
['558']
['558']
['103'
'2'
'11'
'28'
'24']
['574']
['2'
'11'
'28'
'24']
['562'
'526'
'12']
['571'
'581']
['574']
['562'
'526']
['582'
'1']
['560']
['558']
['571']
['558']
['561'
'565'
'570'
'586'
'556'
'558'
'581']
['574']
['11'
'67-1번'
'28'
'24']
['562'
'579']
['11'
'28'
'24']
['12']
['574'
'565'
'582'
'584-1'
'556'
'583']
['560']
['579']
['556']
['43-1번']
['556']
['12'
'579']
['558']
['103']
['574'
'582']
['103'
'14-1번'
'567'
'556']
['2'
'45'
'47'
'111-2'
'11'
'34'
'46'
'12'
'30'
'43']
['11'
'24-1번'
'67-1번'
'28'
'24']
['574']
['302'
'302B'
'급행95'
'551'
'급행97']
['555']
['12']
['302'
'302B'
'562'
'23'
'79'
'67-1번'
'526'
'12'
'인천e음61'
'579']
['574']
['12'
'579']
['1200'
'556']
['574'
'565'
'585'
'582'
'584-1'
'556'
'571'
'583']
['561'
'565'
'570'
'586'
'556'
'558'
'581'
'557'
'557A']
['562'
'79'
'526'
'12'
'인천e음61']
['571']
['11'
'24-1번'
'67-1번'
'28'
'556'
'24']
['35'
'10'
'23'
'24-1번']
['11'
'24-1번'
'67-1번'
'28'
'556'
'24']
['574'
'585'
'111-2'
'582'
'584-1'
'551'
'583'
'560']
['574']
['574']
['558']
['35'
'10'
'45'
'23'
'24-1번']
['558']
['579']
['103'
'14-1번'
'567'
'556']
['574'
'574']
['103'
'14-1번'
'567'
'556']
['24-1번']
['561'
'570'
'586'
'555'
'558'
'581'
'557'
'557A']
['2'
'47'
'111'
'111-2'
'111B'
'582'
'584-1'
'11'
'34'
'46'
'12'
'30'
'112'
'43'
'560']
['11'
'24-1번'
'67-1번'
'28'
'556'
'24']
['2'
'45'
'47'
'111'
'111-2'
'11'
'34'
'46'
'12'
'30'
'112'
'43']
['574'
'585']
['11'
'24-1번'
'67-1번'
'28'
'556'
'24']
['561'
'570'
'555'
'556'
'558'
'581'
'557'
'557A']
['574'
'582'
'1']
['574'
'582'
'1'
'560']
['302'
'302B'
'23'
'67-1번'
'579'
'579']
['24-1번']
['35'
'10'
'582'
'584-1'
'23'
'24-1번']
['558']
['24-1번']
['558']
['103'
'14-1번'
'567'
'556']
['35'
'10'
'45'
'23'
'24-1번']
['569'
'569'
'570'
'570']
['586']
['579']
['103'
'14-1번'
'567'
'556']
['569'
'570']
['556'
'558'
'581']
['579']
['565'
'584-1'
'571'
'583']
['1400'
'47'
'9500'
'585'
'111-2'
'551'
'11'
'46'
'43'
'571'
'583']
['9300'
'37']
['561'
'45'
'47'
'565'
'11'
'1'
'46'
'12'
'43'
'579']
['561'
'45'
'47'
'11'
'1'
'46'
'43']
['569'
'570']
['561'
'45'
'1400'
'47'
'570'
'586'
'11'
'555'
'46'
'43'
'558'
'581'
'557'
'557A']
['569'
'570']
['582'
'556'
'579']
['574'
'582'
'584-1'
'560']
['562'
'79'
'526'
'12'
'인천e음61']
['562'
'79'
'526'
'12'
'인천e음61']
['103-1'
'47'
'37']
['103-1'
'37'
'12']
['569'
'570']
['569'
'570']
['103-1'
'37'
'12']
['302'
'302B'
'561'
'574'
'45'
'47'
'9500'
'585'
'551'
'11'
'1'
'46'
'12'
'43'
'558']
['574'
'582'
'1']
['103-1'
'37'
'12']
['12']
['569'
'570']
['103'
'14-1번'
'567'
'24-1번'
'556']
['574'
'582'
'1'
'560']
['561']
['14-1번'
'11'
'12']
['561']
['103'
'14-1번'
'569'
'570'
'567'
'556']
['302'
'35'
'10'
'2'
'111'
'111-2'
'111B'
'23'
'24-1번'
'1'
'34'
'30'
'112']
['302'
'302B'
'574'
'35'
'10'
'23'
'24-1번'
'1']
['561']
['561']
['103-1'
'561'
'562'
'79'
'37'
'526'
'인천e음61']
['574'
'570'
'582'
'556'
'557'
'557A'
'560']
['103-1'
'561'
'562'
'79'
'37'
'526'
'인천e음61']
['2'
'111'
'111-2'
'570'
'582'
'34'
'30'
'112'
'556'
'557'
'557A']
['45'
'급행95'
'47'
'11'
'1'
'46'
'급행97'
'43']
['45'
'급행95'
'1'
'46'
'급행97'
'43']
['569'
'570']
['561']
['569'
'570']
['561']
['302'
'574'
'35'
'10'
'2'
'1400'
'111'
'111-2'
'111B'
'570'
'582'
'23'
'24-1번'
'1'
'34'
'30'
'112'
'556'
'560']
['24-1번']
['103'
'14-1번'
'567'
'20'
'20A'
'556']
['24-1번']
['14-1번'
'561'
'562'
'47'
'79'
'37']
['14-1번'
'561'
'562'
'47'
'79'
'37']
['45'
'1'
'43']
['45']
['569'
'570']
['569'
'570']
['302'
'35'
'10'
'2'
'111'
'111-2'
'111B'
'23'
'24-1번'
'34'
'30'
'112']
['14-1번'
'561'
'562'
'47'
'79'
'11'
'37']
['103-1'
'14-1번'
'561'
'562'
'47'
'79'
'11'
'37']
['302'
'302B'
'35'
'10'
'2'
'111'
'111-2'
'570'
'23'
'24-1번'
'34'
'30'
'112'
'556']
['564'
'564-2'
'564-2']
['564'
'564-2']
['103-1'
'14-1번'
'1300'
'1301'
'1302'
'47'
'급행99'
'11'
'16-1번'
'8'
'8A'
'30']
['570'
'556']
['24-1번']
['24-1번']
['103'
'14-1번'
'567'
'20'
'20A'
'556']
['557'
'557A']
['570']
['103-1'
'14-1번'
'1300'
'1301'
'1302'
'47'
'급행99'
'11'
'16-1번'
'8'
'8A'
'30']
['45'
'1'
'43']
['14-1번'
'561'
'562'
'37']
['14-1번'
'561'
'562'
'1'
'37'
'43']
['569'
'570']
['45']
['557A']
['14-1번'
'561'
'562'
'37']
['103'
'14-1번'
'567'
'20'
'20A'
'556']
['103'
'14-1번'
'567'
'20'
'20A'
'556']
['14-1번'
'561'
'562'
'1'
'37'
'43']
['14-1번'
'561'
'562'
'37']
['14-1번'
'561'
'562'
'1'
'37'
'43']
['14-1번'
'47'
'11'
'16-1번'
'8'
'8A'
'30']
['557A']
['24-1번']
['302'
'35'
'10'
'2'
'1400'
'111'
'111-2'
'111B'
'23'
'24-1번'
'34'
'30'
'112'
'556'
'564'
'564-2']
['24-1번']
['14-1번'
'45'
'37'
'557']
['14-1번'
'45'
'37']
['569']
['14-1번'
'47'
'11'
'16-1번'
'8'
'8A'
'30']
['103'
'14-1번'
'567'
'20'
'20A'
'556']
['103'
'14-1번'
'567'
'20'
'20A'
'556']
['561'
'562'
'557'
'557A']
['561'
'562'
'557'
'557A']
['24-1번']
['569']
['24-1번']
['564'
'564-2']
['561'
'562'
'557'
'557A']
['24-1번']
['14-1번'
'45'
'37']
['302'
'103'
'35'
'10'
'111'
'111B'
'23'
'112']
['302'
'302B'
'103'
'35'
'10'
'111'
'23'
'112']
['569'
'567'
'539'
'556'
'564'
'564-1'
'564-2']
['14-1번'
'2'
'111-2'
'34'
'20'
'20A'
'30']
['14-1번'
'2'
'111-2'
'34'
'20'
'20A'
'30']
['539'
'564'
'564-1'
'564-2']
['14-1번'
'45']
['302'
'302B'
'103'
'35'
'10'
'111'
'23'
'112']
['302'
'103'
'35'
'10'
'111'
'111B'
'23'
'112']
['14-1번'
'2'
'111-2'
'34'
'20'
'20A'
'30']
['2'
'111-2'
'34'
'30']
['564'
'564-1']
['302'
'103'
'35'
'10'
'111'
'111B'
'23'
'112'
'530']
['302'
'302B'
'103'
'35'
'10'
'111'
'23'
'112']
['539'
'564-2']
['2'
'45'
'1400'
'111-2'
'34'
'30']
['564']
['42'
'3-2번']
['564']
['539'
'564-2']
['302'
'103'
'35'
'10'
'111'
'111B'
'23'
'112'
'530']
['302'
'302B'
'103'
'35'
'10'
'111'
'23'
'112']
['564']
['2'
'45'
'111-2'
'34'
'30']
['42'
'3-2번']
['42'
'592'
'3-2번'
'593']
['530']
['103'
'10'
'42'
'592'
'530'
'593']
['103'
'10'
'42'
'592'
'530'
'593']
['103'
'10'
'42'
'592'
'530'
'593']
['302'
'103'
'35'
'111'
'111B'
'23'
'3-2번'
'112']
['103'
'10'
'42'
'592'
'530'
'593']
['564']
['302'
'302B'
'103'
'35'
'111'
'23'
'112']
['564']
['564']
['564']
['564']
['564']
['103'
'10'
'42'
'592']
['538'
'539']
['302'
'103'
'35'
'111'
'111B'
'23'
'3-2번'
'112']
['2'
'45'
'1400'
'111-2'
'533'
'532'
'535'
'536'
'537'
'538'
'34'
'30'
'564-2']
['564']
['302'
'302B'
'103'
'35'
'111'
'23'
'3-2번'
'112']
['564']
['103']
['103']
['564']
['564']
['103'
'10'
'42'
'592']
['306'
'306A'
'307']
['35'
'23'
'3-2번']
['35'
'23'
'3-2번']
['303'
'303-1'
'304'
'103-1'
'304']
['303'
'303-1'
'304'
'103-1'
'304']
['564']
['103-1']
['564']
['303'
'304'
'103'
'103-1'
'42'
'592'
'304']
['103-1']
['303'
'304'
'103'
'103-1'
'42'
'592'
'62']

In [14]:
a=[]
for i in range(len(df2['노선번호'])):
    cnt=0
    for j in range(len(df2['노선번호'][i])):
        cnt=cnt+1
    a.append(cnt)
a

[3,
 2,
 8,
 3,
 1,
 3,
 3,
 1,
 7,
 5,
 2,
 1,
 1,
 3,
 2,
 2,
 2,
 3,
 2,
 3,
 1,
 1,
 1,
 6,
 6,
 2,
 3,
 1,
 3,
 5,
 2,
 1,
 3,
 3,
 3,
 5,
 5,
 6,
 2,
 2,
 6,
 5,
 5,
 2,
 2,
 2,
 1,
 2,
 2,
 2,
 4,
 3,
 6,
 6,
 1,
 2,
 2,
 3,
 6,
 11,
 6,
 11,
 8,
 9,
 1,
 5,
 8,
 4,
 1,
 3,
 1,
 1,
 4,
 5,
 5,
 3,
 6,
 4,
 2,
 3,
 8,
 6,
 6,
 3,
 2,
 3,
 1,
 1,
 1,
 1,
 1,
 2,
 3,
 4,
 3,
 2,
 5,
 3,
 12,
 14,
 6,
 5,
 9,
 9,
 20,
 16,
 6,
 7,
 5,
 6,
 3,
 1,
 13,
 2,
 3,
 6,
 2,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 4,
 1,
 1,
 4,
 1,
 6,
 2,
 5,
 5,
 8,
 8,
 2,
 5,
 8,
 5,
 8,
 5,
 2,
 3,
 3,
 1,
 2,
 1,
 5,
 6,
 5,
 2,
 1,
 2,
 4,
 5,
 1,
 7,
 5,
 3,
 2,
 1,
 3,
 4,
 6,
 5,
 1,
 3,
 4,
 2,
 3,
 5,
 4,
 5,
 1,
 1,
 4,
 3,
 3,
 2,
 5,
 3,
 4,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 3,
 4,
 1,
 1,
 1,
 2,
 1,
 3,
 4,
 3,
 6,
 5,
 5,
 2,
 2,
 5,
 1,
 3,
 2,
 2,
 3,
 1,
 4,
 5,
 4,
 6,
 3,
 3,
 6,
 3,
 2,
 4,
 3,
 3,
 2,
 3,
 4,
 3,
 3,
 8,
 3,
 1,
 3,
 2,
 2,
 3,
 2,
 6,
 8,
 4,
 2,
 4,
 4,
 1,
 1,
 2,
 3,
 3,
 4,
 3,
 2,
 1,
 2,
 5,
 6,
 3,
 7,
 4,
 1,
 2,
 3,
 3,
 12,
 5,
 4,
 2,
 4,
 5,
 3,
 4,
 1,
 5,
 4,
 4,
 7,
 6,
 3,
 1,
 4,
 6,
 6,
 6,
 4,
 5,
 1,
 1,
 6,
 1,
 3,
 3,
 2,
 4,
 1,
 5,
 6,
 2,
 5,
 1,
 3,
 4,
 1,
 3,
 6,
 4,
 1,
 7,
 3,
 3,
 1,
 3,
 13,
 16,
 3,
 1,
 2,
 5,
 1,
 1,
 2,
 1,
 2,
 4,
 19,
 2,
 1,
 4,
 1,
 3,
 2,
 3,
 3,
 3,
 9,
 8,
 8,
 3,
 3,
 1,
 2,
 7,
 4,
 4,
 5,
 8,
 6,
 3,
 2,
 7,
 1,
 1,
 7,
 3,
 2,
 10,
 7,
 3,
 3,
 3,
 13,
 6,
 1,
 7,
 2,
 6,
 3,
 6,
 6,
 1,
 3,
 1,
 3,
 5,
 3,
 5,
 6,
 2,
 1,
 4,
 2,
 4,
 6,
 4,
 3,
 3,
 7,
 14,
 2,
 1,
 2,
 18,
 1,
 1,
 5,
 1,
 4,
 3,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 7,
 1,
 4,
 2,
 3,
 1,
 6,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 4,
 10,
 5,
 1,
 5,
 1,
 1,
 10,
 1,
 2,
 2,
 8,
 9,
 5,
 1,
 6,
 4,
 6,
 8,
 1,
 1,
 1,
 5,
 1,
 1,
 4,
 2,
 4,
 1,
 8,
 15,
 6,
 12,
 2,
 6,
 8,
 3,
 4,
 6,
 1,
 6,
 1,
 1,
 1,
 4,
 5,
 4,
 1,
 1,
 4,
 2,
 3,
 1,
 4,
 11,
 2,
 10,
 7,
 2,
 14,
 2,
 3,
 4,
 5,
 5,
 3,
 3,
 2,
 2,
 3,
 15,
 3,
 3,
 1,
 2,
 5,
 4,
 1,
 3,
 1,
 6,
 13,
 8,
 1,
 1,
 7,
 7,
 7,
 11,
 8,
 6,
 2,
 1,
 2,
 1,
 19,
 1,
 6,
 1,
 6,
 6,
 3,
 1,
 2,
 2,
 12,
 7,
 8,
 14,
 3,
 2,
 12,
 2,
 1,
 1,
 6,
 2,
 1,
 12,
 3,
 4,
 6,
 2,
 1,
 1,
 4,
 6,
 6,
 6,
 4,
 6,
 7,
 1,
 1,
 16,
 1,
 4,
 3,
 1,
 7,
 6,
 6,
 4,
 4,
 1,
 1,
 1,
 2,
 4,
 1,
 3,
 8,
 8,
 7,
 7,
 7,
 4,
 2,
 8,
 8,
 7,
 4,
 2,
 9,
 8,
 2,
 6,
 1,
 2,
 1,
 2,
 9,
 8,
 1,
 5,
 2,
 4,
 1,
 6,
 6,
 6,
 8,
 6,
 1,
 7,
 1,
 1,
 1,
 1,
 1,
 4,
 2,
 8,
 13,
 1,
 8,
 1,
 1,
 1,
 1,
 1,
 4,
 3,
 3,
 3,
 5,
 5,
 1,
 1,
 1,
 7,
 1,
 7]

In [15]:
df2['버스수'] = a

In [16]:
df2

,정류소명,정류소아이디,정류소주소,노선아이디,정류소번호,노선번호,평균 배차 간격,최대 배차 간격,도로명,도로폭,도로폭_숫자,버스수
0,진산과학고등학교,166000915,인천광역시 부평구 굴포로 208 버스정류장,165000112,40915,"[['565', '555', '558']]",13.33,17,굴포로,30.0,9.0,3
1,삼산주공1단지(상가앞),166000908,인천광역시 부평구 평천로 443 버스정류장,165000013,40908,"[['10', '34']]",13.00,15,평천로,25.0,8.0,2
2,희망체육공원입구,166000912,인천광역시 부평구 경인로 840 버스정류장,165000107,40912,"[['561', '561', '562', '562', '557', '557', '5...",23.00,35,경인로,35.0,10.0,8
3,인천성모병원종점지주차장,166000919,인천광역시 부평구 동수로 68 버스정류장,165000053,40919,"[['79', '1', '43']]",16.00,18,동수로,20.0,7.0,3
4,열우물보조경기장주차장,166000916,인천광역시 부평구 열우물로150번길 64 버스정류장,165000111,40916,[['564-1']],24.00,24,열우물로,27.5,8.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
640,종근당,166000005,인천광역시 부평구 백범로 486 버스정류장,165000216,40005,[['103-1']],15.00,15,백범로,35.0,10.0,1
641,형제마트,166000004,인천광역시 부평구 정석로 6 버스정류장,165000110,40004,[['564']],12.00,12,정석로,10.0,4.0,1
642,동암사거리,166000003,인천광역시 부평구 백범로 452 버스정류장,165000219,40003,"[['303', '304', '103', '103-1', '42', '592', '...",15.57,20,백범로,35.0,10.0,7
643,종근당,166000002,인천광역시 부평구 백범로 481 버스정류장,165000216,40002,[['103-1']],15.00,15,백범로,35.0,10.0,1
644,동암사거리,166000001,인천광역시 부평구 백범로 453 버스정류장,165000219,40001,"[['303', '304', '103', '103-1', '42', '592', '...",14.00,20,백범로,35.0,10.0,7

In [17]:
df3 = pd.read_csv('../data/전처리데이터/부평구 정류장명 및 위치와 버스_최종.csv',encoding='cp949')
df3

,정류소명,정류소아이디,정류소주소,노선아이디,정류소번호,노선번호,평균 배차 간격,최대 배차 간격,도로명,도로폭,도로폭_숫자
0,진산과학고등학교,166000915,인천광역시 부평구 굴포로 208 버스정류장,165000112,40915,"['565', '555', '558']",13.33,17,굴포로,30.0,9.0
1,삼산주공1단지(상가앞),166000908,인천광역시 부평구 평천로 443 버스정류장,165000013,40908,"['10', '34']",13.00,15,평천로,25.0,8.0
2,희망체육공원입구,166000912,인천광역시 부평구 경인로 840 버스정류장,165000107,40912,"['561', '561', '562', '562', '557', '557', '55...",23.00,35,경인로,35.0,10.0
3,인천성모병원종점지주차장,166000919,인천광역시 부평구 동수로 68 버스정류장,165000053,40919,"['79', '1', '43']",16.00,18,동수로,20.0,7.0
4,열우물보조경기장주차장,166000916,인천광역시 부평구 열우물로150번길 64 버스정류장,165000111,40916,['564-1'],24.00,24,열우물로,27.5,8.0
...,...,...,...,...,...,...,...,...,...,...,...
640,종근당,166000005,인천광역시 부평구 백범로 486 버스정류장,165000216,40005,['103-1'],15.00,15,백범로,35.0,10.0
641,형제마트,166000004,인천광역시 부평구 정석로 6 버스정류장,165000110,40004,['564'],12.00,12,정석로,10.0,4.0
642,동암사거리,166000003,인천광역시 부평구 백범로 452 버스정류장,165000219,40003,"['303', '304', '103', '103-1', '42', '592', '3...",15.57,20,백범로,35.0,10.0
643,종근당,166000002,인천광역시 부평구 백범로 481 버스정류장,165000216,40002,['103-1'],15.00,15,백범로,35.0,10.0
644,동암사거리,166000001,인천광역시 부평구 백범로 453 버스정류장,165000219,40001,"['303', '304', '103', '103-1', '42', '592', '62']",14.00,20,백범로,35.0,10.0

In [18]:
df3['버스수'] = a
df3

,정류소명,정류소아이디,정류소주소,노선아이디,정류소번호,노선번호,평균 배차 간격,최대 배차 간격,도로명,도로폭,도로폭_숫자,버스수
0,진산과학고등학교,166000915,인천광역시 부평구 굴포로 208 버스정류장,165000112,40915,"['565', '555', '558']",13.33,17,굴포로,30.0,9.0,3
1,삼산주공1단지(상가앞),166000908,인천광역시 부평구 평천로 443 버스정류장,165000013,40908,"['10', '34']",13.00,15,평천로,25.0,8.0,2
2,희망체육공원입구,166000912,인천광역시 부평구 경인로 840 버스정류장,165000107,40912,"['561', '561', '562', '562', '557', '557', '55...",23.00,35,경인로,35.0,10.0,8
3,인천성모병원종점지주차장,166000919,인천광역시 부평구 동수로 68 버스정류장,165000053,40919,"['79', '1', '43']",16.00,18,동수로,20.0,7.0,3
4,열우물보조경기장주차장,166000916,인천광역시 부평구 열우물로150번길 64 버스정류장,165000111,40916,['564-1'],24.00,24,열우물로,27.5,8.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
640,종근당,166000005,인천광역시 부평구 백범로 486 버스정류장,165000216,40005,['103-1'],15.00,15,백범로,35.0,10.0,1
641,형제마트,166000004,인천광역시 부평구 정석로 6 버스정류장,165000110,40004,['564'],12.00,12,정석로,10.0,4.0,1
642,동암사거리,166000003,인천광역시 부평구 백범로 452 버스정류장,165000219,40003,"['303', '304', '103', '103-1', '42', '592', '3...",15.57,20,백범로,35.0,10.0,7
643,종근당,166000002,인천광역시 부평구 백범로 481 버스정류장,165000216,40002,['103-1'],15.00,15,백범로,35.0,10.0,1
644,동암사거리,166000001,인천광역시 부평구 백범로 453 버스정류장,165000219,40001,"['303', '304', '103', '103-1', '42', '592', '62']",14.00,20,백범로,35.0,10.0,7

In [19]:
df3.to_csv('../data/전처리데이터/부평구 정류장명 및 위치와 버스_최종_버스수 추가.csv', encoding = 'cp949', index=None)